version: '3.8'

services:
  postgres:
    image: postgres:16.2
    ports:
      - "54032:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: words_of_wisdom_POW
    networks:
      - words-of-wisdom-POW-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  words-of-wisdom-POW-network:
    external: true

volumes:
  postgres_data:
