version: '3.8'

services:
  words-of-wisdom-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: words-of-wisdom-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .env.docker:/app/.env
    networks:
      - words-of-wisdom-network
    restart: always

  words-of-wisdom-client:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: words-of-wisdom-client
    depends_on:
      - words-of-wisdom-server
    env_file:
      - .env
    volumes:
      - .env.docker:/app/.env
    networks:
      - words-of-wisdom-network
    restart: always

networks:
  words-of-wisdom-network:
    driver: bridge
