// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// GetQuoteByID provides a mock function with given fields: id
func (_m *Storage) GetQuoteByID(id int) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuoteByID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetQuoteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuoteByID'
type Storage_GetQuoteByID_Call struct {
	*mock.Call
}

// GetQuoteByID is a helper method to define mock.On call
//   - id int
func (_e *Storage_Expecter) GetQuoteByID(id interface{}) *Storage_GetQuoteByID_Call {
	return &Storage_GetQuoteByID_Call{Call: _e.mock.On("GetQuoteByID", id)}
}

func (_c *Storage_GetQuoteByID_Call) Run(run func(id int)) *Storage_GetQuoteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Storage_GetQuoteByID_Call) Return(_a0 string, _a1 error) *Storage_GetQuoteByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetQuoteByID_Call) RunAndReturn(run func(int) (string, error)) *Storage_GetQuoteByID_Call {
	_c.Call.Return(run)
	return _c
}

// QuotesLength provides a mock function with given fields:
func (_m *Storage) QuotesLength() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for QuotesLength")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Storage_QuotesLength_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuotesLength'
type Storage_QuotesLength_Call struct {
	*mock.Call
}

// QuotesLength is a helper method to define mock.On call
func (_e *Storage_Expecter) QuotesLength() *Storage_QuotesLength_Call {
	return &Storage_QuotesLength_Call{Call: _e.mock.On("QuotesLength")}
}

func (_c *Storage_QuotesLength_Call) Run(run func()) *Storage_QuotesLength_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_QuotesLength_Call) Return(_a0 int) *Storage_QuotesLength_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_QuotesLength_Call) RunAndReturn(run func() int) *Storage_QuotesLength_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
