// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// QuoteGetter is an autogenerated mock type for the quoteGetter type
type QuoteGetter struct {
	mock.Mock
}

type QuoteGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *QuoteGetter) EXPECT() *QuoteGetter_Expecter {
	return &QuoteGetter_Expecter{mock: &_m.Mock}
}

// GetRandomQuote provides a mock function with given fields: ctx
func (_m *QuoteGetter) GetRandomQuote(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomQuote")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QuoteGetter_GetRandomQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomQuote'
type QuoteGetter_GetRandomQuote_Call struct {
	*mock.Call
}

// GetRandomQuote is a helper method to define mock.On call
//   - ctx context.Context
func (_e *QuoteGetter_Expecter) GetRandomQuote(ctx interface{}) *QuoteGetter_GetRandomQuote_Call {
	return &QuoteGetter_GetRandomQuote_Call{Call: _e.mock.On("GetRandomQuote", ctx)}
}

func (_c *QuoteGetter_GetRandomQuote_Call) Run(run func(ctx context.Context)) *QuoteGetter_GetRandomQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *QuoteGetter_GetRandomQuote_Call) Return(_a0 string, _a1 error) *QuoteGetter_GetRandomQuote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QuoteGetter_GetRandomQuote_Call) RunAndReturn(run func(context.Context) (string, error)) *QuoteGetter_GetRandomQuote_Call {
	_c.Call.Return(run)
	return _c
}

// NewQuoteGetter creates a new instance of QuoteGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuoteGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuoteGetter {
	mock := &QuoteGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
